name: CI

on:
- push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Prepare test environment
      env:
        PHPIPAM_URL: ${{ secrets.PHPIPAM_URL }}
        PHPIPAM_APPID: ${{ secrets.PHPIPAM_APPID }}
        PHPIPAM_USERNAME: ${{ secrets.PHPIPAM_USERNAME }}
        PHPIPAM_PASSWORD: ${{ secrets.PHPIPAM_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        make test-setup
    - name: Run all tests
      run:
        make test-all
